### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST https://localhost:9999/api/userreg
Content-Type: application/json
Accept: application/json

{
  "username": "exampleUsername",
  "password": "examplePassword123!",
  "againPassword": "examplePassword",
  "name" : "spdla",
  "email" : "sadlk@asldk"
}
